version: "3"

services:
    kimoji-upload-music:
        container_name: kimoji-upload-music
        image: 782042369/kimoji-upload-music:v1.3
        hostname: kimoji-upload-music
        volumes:
          - /www/xxx:/app/public/uploads
        ports:
            - 13030:3000
        restart: always
        network_mode: bridge
